#!/usr/bin/env python3
"""M7: the old Portents stylesheets, scoped under `.pf-doc` → campaign/site/campaign.css.

The campaign's documents render inside the VTT's pages, whose own stylesheet defines some of the
same custom properties (--paper, --ink, --edge, --jade) and styles the same elements. Scoping
every rule to `.pf-doc` — the element each campaign document is drawn into — keeps the parchment
where it was and leaves the VTT's pages untouched: `:root`, `html` and `body` become `.pf-doc`
itself, every other selector a descendant of it. @media / @supports are scoped inside; @keyframes
and @font-face are copied as they are. Nothing but selectors changes.

    python3 campaign/source/scope_css.py

Sources: campaign/source/css/*.css, in the order below. Proves the output: every declaration block
of the sources appears in the output, the same number of times, and every output selector starts
with `.pf-doc`.
"""
import os
import re
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "css")
OUT = os.path.join(os.path.dirname(HERE), "site", "campaign.css")
ORDER = ["rokugan.css", "chronicle.css", "map.css", "dramatis.css"]
SCOPE = ".pf-doc"


def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(css):
    """Top-level (prelude, body) pairs; body is the text between the matched braces."""
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            if css[i:].strip():
                raise SystemExit("stray text: %r" % css[i:][:80])
            break
        depth, k = 1, j + 1
        while depth:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k
    return out


def scope_selector(sel):
    sel = sel.strip()
    m = re.match(r"^(:root|html|body)\b(.*)$", sel)
    if m:
        return SCOPE + m.group(2)
    return SCOPE + " " + sel


def scope(css, decls):
    out = []
    for pre, body in blocks(css):
        if pre.startswith("@media") or pre.startswith("@supports"):
            out.append(pre + "{\n" + scope(body, decls) + "}")
        elif pre.startswith("@"):
            out.append(pre + "{" + body + "}")
        else:
            decls.append(body.strip())
            out.append(",".join(scope_selector(s) for s in pre.split(",")) + "{" + body + "}")
    return "\n".join(out) + "\n"


def main():
    src_decls, text = [], []
    for name in ORDER:
        css = strip_comments(open(os.path.join(SRC, name), encoding="utf-8").read())
        text.append("/* ── %s ── */\n" % name + scope(css, src_decls))
    head = ("/* campaign/site/campaign.css — GENERATED by campaign/source/scope_css.py from campaign/source/css/;\n"
            "   do not edit by hand. Every rule is scoped to .pf-doc, the element a campaign document is drawn into. */\n")
    out = head + "\n".join(text)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    # proof
    got_decls, bad = [], 0

    def walk(css):
        nonlocal bad
        for pre, body in blocks(css):
            if pre.startswith("@media") or pre.startswith("@supports"):
                walk(body)
            elif not pre.startswith("@"):
                got_decls.append(body.strip())
                for s in pre.split(","):
                    if not s.strip().startswith(SCOPE):
                        bad += 1
                        print("UNSCOPED: %s" % s.strip())
    walk(strip_comments(out))
    if Counter(got_decls) != Counter(src_decls):
        bad += 1
        print("DECLARATIONS DIFFER")
    print("scope_css: %d rules from %d files → %s; every declaration block kept, every selector under %s: %s"
          % (len(got_decls), len(ORDER), os.path.relpath(OUT, os.getcwd()), SCOPE, "OK" if not bad else "FAILED (%d)" % bad))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
